version: "2"
services:

    database_server:
        container_name: database_server
        image: mongo
        environment:
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: password
        volumes:
            - database_server_data:/data/db

    database_admin:
        container_name: database_server_admin
        image: mongo-express
        environment:
            ME_CONFIG_MONGODB_SERVER: database_server
            ME_CONFIG_BASICAUTH_USERNAME: admin
            ME_CONFIG_BASICAUTH_PASSWORD: password
            ME_CONFIG_MONGODB_ADMINUSERNAME: admin
            ME_CONFIG_MONGODB_ADMINPASSWORD: password
        depends_on:
            - database_server
        ports:
            - 8081:8081

volumes:
    database_server_data: