version: '3'

services:
    api:
        container_name: node_kong_api
        build: "."        
        ports:
            - "8004:8004"
        networks:
            - kong-net
    kong-database:
        container_name: kong-database
        image: 'postgres:9.6'
        working_dir: /usr/app
        volumes:
            - ${PWD}/postgres/data:/var/lib/postgresql/data
        restart: always
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: 12345
            POSTGRES_DB : kong_db
        ports:
            - "5432:5432"
        healthcheck:
            test: ["CMD", "pg_isready", "-U", "user"]
            interval: 5s
            timeout: 5s
            retries: 5
        networks:
            - kong-net
    kong:
        container_name: kong
        image: kong:latest
        restart: always
        environment:
            KONG_LOG_LEVEL: debug
            KONG_DATABASE: postgres
            KONG_PG_HOST: kong-database
            KONG_PG_DATABASE: kong_db
            KONG_PG_USER: user
            KONG_PG_PASSWORD: 12345
            KONG_PROXY_ACCESS_LOG: /dev/stdout
            KONG_ADMIN_ACCESS_LOG: /dev/stdout
            KONG_PROXY_ERROR_LOG: /dev/stderr
            KONG_ADMIN_ERROR_LOG: /dev/stderr
            KONG_ADMIN_LISTEN: 0.0.0.0:8001
            KONG_PROXY_LISTEN: 0.0.0.0:8000
            KONG_PROXY_LISTEN_SSL: 0.0.0.0:8443
        depends_on:
            - kong-database
            - api
        healthcheck:
            test: ["CMD", "kong", "health"]
            interval: 10s
            timeout: 10s
            retries: 10          
        ports:
            - "8000:8000/tcp"
            - "8001:8001/tcp"
            - "8443:8443/tcp"
            - "8444:8444/tcp"
        networks:
            - kong-net
    konga:
        container_name: konga
        image: pantsel/konga:next
        restart: always
        environment:
            DB_ADAPTER: postgres
            DB_HOST: kong-database
            DB_USER: user
            DB_PASSWORD: 12345
            TOKEN_SECRET: km1GUr4RkcQD7DewhJPNXrCuZwcKmqjb
            DB_DATABASE: konga_db
            NODE_ENV: production
        networks:
            - kong-net
        depends_on:
            - kong-database
            - kong
        ports:
            - "1337:1337"
networks:
  kong-net:
    driver: bridge

# docker exec -it product_db bash
# psql postgres -U user -p 5432 product_db
